// Common color names and a error color scheme.
export const BLACK = "color: black",
  SILVER = "color: silver",
  GRAY = "color: gray",
  WHITE = "color: white",
  MAROON = "color: maroon",
  RED = "color: red",
  PURPLE = "color: purple",
  FUCHSIA = "color: fuchsia",
  GREEN = "color: green",
  LIME = "color: lime",
  OLIVE = "color: olive",
  YELLOW = "color: yellow",
  NAVY = "color: navy",
  BLUE = "color: blue",
  TEAL = "color: teal",
  AQUA = "color: aqua",
  ORANGE = "color: orange",
  ERROR_COLOR = "color: white; background-color: red";

/* there are 150 additional colors defined, I'll type them up later later.
See: https://developer.mozilla.org/en-US/docs/Web/CSS/named-color
    ICEBLUE = 'color: iceblue',
    ANTIQUEWHITE = 'color: antiquewhite',
    AQUAMARINE = 'color: aquamarine',
    AZURE = 'color: azure',
    BEIGE = 'color: beige',
    BISQUE = 'color: bisque',
    BLANCHEALMOND = 'color: blanchedalmond',
    BLUEVIOLET = 'color: blueviolet',
    BROWN = 'color: brown',
    BURLYWOOD = 'color: burlywood',
    CADETBLUE = 'color: cadetblue',
    CHARTREUSE = 'color: chartreuse',
    CHOCOLATE = 'color: chocolate',
    CORAL = 'color: coral',
    CORNFLOWERBLUE = 'color: cornflowerblue',
    CORNSILK = 'color: cornsilk',
    CRIMSON = 'color: crimson',
    CYAN = AQUA,
    DARKBLUE = 'color: darkblue',
    DARKCYAN = 'color: darkcyan',
    DARKGOLDENROLD = 'color: darkgoldenrod',
    DARKGRAY = 'color: darkgray',
    DARKGREEN = 'color: darkgreen',
    DARKGREY = DARKGRAY,
    DARKKHAKI = 'color: darkkhaki',
    DARKMAGENTA = 'color: darkmagenta',
    DARKOLIVEGREEN = 'color: darkolivegreen',
*/
